### ISSUE TITLE
Advanced Options no longer there?

### ISSUE THREAD

**Issue by gingerbeardman** [JusticeRage/twitter-blocklist#1]
I see this

![58419400-6c255300-8082-11e9-87ad-3b0cc0c09ffd](https://user-images.githubusercontent.com/49612/58419530-c7574580-8082-11e9-981b-3153f0e66624.png)

**Comment by JusticeRage** [comment]
Hi! This is different from the page I have at https://twitter.com/settings/blocked where the option is still present. You might be using the mobile version of Twitter where the option is not shown?

**Comment by gingerbeardman** [comment]
I think I've been moved to "new twitter"? which I think is more like mobile than the old one.

for me https://twitter.com/settings/blocked redirects to https://twitter.com/settings/blocked/all

I've asked twitter support. Thanks!

**Comment by k4nfr3** [comment]
Hello, any news on this ? I have the same redirect to https://twitter.com/settings/blocked/all which doesn't allow to import lists.
Regards

**Comment by JusticeRage** [comment]
Yes, the new Twitter design [doesn't provide this option anymore](https://help.twitter.com/en/using-twitter/advanced-twitter-block-options).
Until they decide to fix this, you'll need to use a browser extension such as [GoodTwitter](https://addons.mozilla.org/fr/firefox/addon/goodtwitter/) to get the feature back.

**Comment by gingerbeardman** [comment]
What's the resolution of this issue being closed?

**Comment by JusticeRage** [comment]
A script is provided replace the missing functionalities from Twitter! 
________________________________

**Comment by gingerbeardman** [comment]
Awesome, thank you!
